version: "3.9"

services:
  postgres:
    image: "postgres:latest"
    container_name: "pg-docker"
    ports:
    - "5432:5432"
    volumes:
    - /docker/volumes/pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 1234
volumes:
  pg_data: {}
