version: '3.9'
services:
  db:
    image: mysql:latest
    container_name: ms_docker
    ports:
      - 3306:3306
    volumes: 
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: test
      MYSQL_PASSWORD: 1234
volumes:
  db_data: {}
